### ISSUE TITLE
Wrong ligature mappings

### ISSUE THREAD

**Issue by truls** [johnw42/fira-code-emacs#4]
Hi,

I've been using this package successfully since it's release without any issues. However, I just tried installing again on another system using a clean checkout of this repo and rerunning `make` to generate `fira-code-data.el`. This time, the ligatures are not correctly mapped/rendered. See for example the first few lines of the `fira-code-data.el` opened in emacs below

```emacs-lisp
;; -*- coding: utf-8 -*-
(defconst fira-code--data
  '(["space.frac" " " "\xe100"]  ;   
    ["exclam_exclam.liga" "!!" "\xe101"]  ;   
    ["exclam_exclam_period.liga" "!!." "\xe102"]  ;   
    ["exclam_equal.liga" "!=" "\xe103"]  ;   
    ["exclam_equal_equal.liga" "!==" "\xe104"]  ;   
    ["numbersign_exclam.liga" "#!" "\xe105"]  ;   
    ["numbersign_numbersign.liga" "##" "\xe106"]  ;   
    ["numbersign_numbersign_numbersign.liga" "###" "\xe107"]  ;   
    ["numbersign_numbersign_numbersign_numbersign.liga" "####" "\xe108"]  ;   

```

**Comment by johnw42** [comment]
The code you pasted looks correct. The ligatures will only display correctly with the special "Fira Emacs" font generated by the build process. Did you remember to copy the font files from the `modified` directory into your `~/.fonts` directory?

**Comment by truls** [comment]
Yes, you're right, sorry. I forgot to copy the generated font files.
