### ISSUE TITLE
fira-code-mode working for all modes except Agda

### ISSUE THREAD

**Issue by boystrange** [johnw42/fira-code-emacs#5]
Thanks for sharing fira-code-mode. I've installed it following the provided instructions and I found that it works beautifully in all modes except the one I'm most interested in (Agda mode). Below are two screenshots:

1. fundamental mode and fira-code-mode enabled, the ligature is shown correctly
2. agda mode and fira-code-mode enabled, the ligature is not shown (but in the mode line there's a ligature!)

I have no issues with fira-code-mode in other languages (C++, Haskell), so I suppose that fira-code-mode and agda-mode step onto each other in some way, but I have no idea where to look for the issue. Any clue that could point me in the right direction?

BTW, I'm on MacOS and use [Emacs for MacOS](https://emacsformacosx.com).
<img width="726" alt="1_fundamental" src="https://user-images.githubusercontent.com/44829871/75623969-07b69780-5bb0-11ea-8253-d26b5f96d0de.png">
<img width="726" alt="2_agda" src="https://user-images.githubusercontent.com/44829871/75623972-0f763c00-5bb0-11ea-926c-8fcb57f5dae1.png">

**Comment by johnw42** [comment]
I don't think it will be easy to make it work, because agda2-mode disables font-lock-mode, which is required for fira-code-mode to work properly. If you manually enable font-lock-mode, the ligatures show up correctly, but I have no idea how that will interact with whatever agda2-mode is doing.

**Comment by boystrange** [comment]
Thank you John. Re-enabling font-lock-mode does indeed show the ligatures correctly. So far I haven't noticed other nasty side effects.
